### ISSUE TITLE
Windows often show only black

### ISSUE THREAD

**Issue by db48x** [foxxbl/shady-search#9]
All of the UI disappears and the window is left completely black. I’d take a screenshot, but there’s not much to see…

There appears to be no particular cause except possibly moving the mouse over the window.

**Comment by foxxbl** [comment]
Hi @db48x , I have added a console edition for debugging purposes.
Please install the version: https://github.com/foxxbl/shady-search/releases/download/1.0.1/X4.Black.Marketeer.Finder-1.0.1-console.msi and attach here the stacktrace from console if there's an exception reported.
Otherwise if you can reproduce it with certainty, please add here the flow which creates this error. Thanks!

**Comment by db48x** [comment]
I think this is fixed by 2.0! Thanks!
